"use strict";
exports.__esModule = true;
exports.usersSeed = void 0;
var role_1 = require("../enums/role");
var user_status_1 = require("../enums/user.status");
var user_type_1 = require("../enums/user.type");
exports.usersSeed = [
    {
        phone: '0000000000',
        active: true,
        enabled: true,
        firstName: 'Бахрам',
        lastName: 'Раджабов',
        role: role_1.Role.DIRECTOR,
        status: user_status_1.UserStatus.EMPLOYEE,
        type: user_type_1.UserType.IP,
        email: 'radzhabovBF@outlook.com',
        passwordHash: '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        middleName: 'Фирузович',
        dateOfBirth: new Date()
    },
    {
        phone: '0000000001',
        active: true,
        enabled: true,
        firstName: 'Наталья',
        lastName: 'Гагарина',
        role: role_1.Role.SDL,
        status: user_status_1.UserStatus.EMPLOYEE,
        type: user_type_1.UserType.IP,
        email: 'sdl@udalton.ru',
        passwordHash: '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        middleName: 'Вячеславовна'
    },
    {
        phone: '9508343250',
        active: true,
        enabled: true,
        firstName: 'Кабрин',
        lastName: 'Андрей',
        role: role_1.Role.INVESTOR,
        status: user_status_1.UserStatus.CLIENT,
        type: user_type_1.UserType.FL,
        email: 'kabrin@mail.ru',
        passwordHash: '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        middleName: 'Ивановна',
        inn: '234535346',
        dateOfBirth: new Date(),
        placeOfBirth: 'г. Томск',
        address: 'Томск, ул. Ленина 23',
        passportNumber: '6879 354684',
        passportIssuedBy: 'ОВД Ленинского района Ижевска',
        passportCodeDepartment: '702-002',
        orgInn: '213534163246',
        orgOgrn: '324523462346у',
        orgName: 'ООО Елена',
        orgLocation: 'г. Томск',
        infoPercent: 'string',
        infoStructure: 'string',
        infoAnnual: 'string',
        infoActivities: 'string',
        infoFacts: 'string',
        infoSums: 'string',
        infoRating: 'string',
        mainAccount: 1000000
    },
    {
        phone: '9508343251',
        active: true,
        enabled: true,
        firstName: 'Михаил',
        lastName: 'Иванов',
        role: role_1.Role.LENDER,
        status: user_status_1.UserStatus.CLIENT,
        type: user_type_1.UserType.UL,
        email: 'a.kabrin@yandex.ru',
        passwordHash: '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        middleName: 'Иванович',
        inn: '234535346',
        dateOfBirth: new Date(),
        placeOfBirth: 'г. Томск',
        address: 'Томск, ул. Ленина 23',
        passportNumber: '6879 354684',
        passportIssuedBy: 'ОВД Ленинского района Ижевска',
        passportCodeDepartment: '702-002',
        orgInn: '213534163246',
        orgOgrn: '324523462346у',
        orgName: 'ООО Миша',
        orgLocation: 'г. Ижевск',
        infoPercent: 'string',
        infoStructure: 'string',
        infoAnnual: 'string',
        infoActivities: 'string',
        infoFacts: 'string',
        infoSums: 'string',
        infoRating: 'string'
    },
];
